version: '3'

services:
  db:
    image: postgres
  web:
    build: .  # This means that docker-compose must use the Dockerfile found in the same directory
    command: python /app/django_in_docker_example_with_compose/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # There are credentials in this .env! Be aware of potential security issues in a real project!
# db -> web
