# Networks, nombres de contenedor

version: '3'

services:
  db:
    container_name: compose-base-de-datos
    image: postgres
    networks:
      - best_network_ever
  web:
    container_name: compose-django-server
    build: .  # Esto significa que docker-compose debe usar el Dockerfile que se encuentra en este mismo directorio
    command: python /app/ejemplo_de_django_en_docker_compose/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - best_network_ever
    depends_on:
      - db

networks:
  best_network_ever:  # El ":" es intencional, ya que más abajo se le podría agregar configuraciones

# db -> web
