# Environment variables

version: '3'

services:
  db:
    container_name: ${DB_CONTAINER_NAME}  # Read the env var "DB_CONTAINER_NAME" from the .env file
    image: postgres
    networks:
      - best_network_ever
  web:
    container_name: ${WEB_CONTAINER_NAME}  # Read the env var "WEB_CONTAINER_NAME" from the .env file
    build: .  # This means that docker-compose must use the Dockerfile found in the same directory
    command: python /app/django_in_docker_example_with_compose/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - best_network_ever
    depends_on:
      - db
    env_file:
      - .env  # There are credentials in this .env! Be aware of potential security issues in a real project!

networks:
  best_network_ever:  # The ":" is intentional, since configurations can be provided below

# db -> web

# Note: even though I say the containers' names are read from the .env file, that is NOT because I specified "env_file" for the web service; compose already exported the variables from the file.
